name: PR Workflow
description: This workflow runs on every pull-request to ensure dart package quality.

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: dart-package
        uses: nikosportolos/dart_package@v0.0.1
