# This workflow runs when publishing a Dart package on pub.dev.
name: Publish Workflow

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: dart-package
        uses: nikosportolos/dart_package@v0.0.2
        with:
          coverage: true
          codecov: true
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          publish: true
          pubdev_token: ${{ secrets.PUBDEV_TOKEN }}
